[build-system]
# AVOID CHANGING REQUIRES: IT WILL BE UPDATED BY PYSCAFFOLD!
requires = ["setuptools>=46.1.0,<50", "setuptools_scm[toml]>=5", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# See configuration details in https://github.com/pypa/setuptools_scm
version_scheme = "no-guess-dev"

[tool.poetry]
name = "datajunction-server"
version = "0.0.1a7"
readme = "README.rst"
repository = "https://github.com/DataJunction/dj"
description = "DataJunction server library for running to a DataJunction server"
authors = ["DataJunction Authors"]
license = "MIT"
packages = [
    { include = "dj" },
]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^5.4.1"
SQLAlchemy-Utils = "^0.37.7"
accept-types = "^0.4.1"
antlr4-python3-runtime = "^4.12.0"
asciidag = "^0.2.0"
cachelib = "^0.4.0"
celery = "^5.2.2"
fastapi= ">=0.70.1"
msgpack = "^1.0.2"
opentelemetry-instrumentation-fastapi = "0.38b0"
python-dotenv = "^0.19.0"
redis = "^3.5.3"
requests = "^2.26.0"
rich = "^10.16.2"
SQLAlchemy = "<= 1.4.41, >= 1.4.17"
sqlmodel = "^0.0.8"
sqlparse = "^0.3.0"
yarl = "^1.7.2"
