[build-system]
# AVOID CHANGING REQUIRES: IT WILL BE UPDATED BY PYSCAFFOLD!
requires = ["setuptools>=46.1.0,<50", "setuptools_scm[toml]>=5", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# See configuration details in https://github.com/pypa/setuptools_scm
version_scheme = "no-guess-dev"

[tool.poetry]
name = "datajunction-server"
version = "0.0.1a7"
readme = "README.rst"
repository = "https://github.com/DataJunction/dj"
description = "DataJunction server library for running to a DataJunction server"
authors = ["DataJunction Authors"]
license = "MIT"
packages = [
    { include = "dj" },
]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^6.0"
SQLAlchemy-Utils = "^0.40.0"
accept-types = "^0.4.1"
antlr4-python3-runtime = "^4.12.0"
asciidag = "^0.2.0"
cachelib = "^0.10.2"
celery = "^5.2.7"
fastapi= "^0.70.1"
msgpack = "^1.0.5"
opentelemetry-instrumentation-fastapi = "0.38b0"
python-dotenv = "^0.19.0"
redis = "^4.5.4"
requests = "^2.28.2"
rich = "^13.3.3"
SQLAlchemy = "^1.4.41"
sqlmodel = "^0.0.8"
sqlparse = "^0.4.3"
yarl = "^1.8.2"

[tool.poetry.group.dev.dependencies]
alembic = "^1.10.3"
codespell = "^2.2.4"
freezegun = "^1.2.2"
pre-commit = "^3.2.2"
pylint = "^2.17.2"
pytest-asyncio = "^0.15.1"
pytest-cov = "^4.0.0"
pytest-integration = "^0.2.2"
pytest-mock = "^3.10.0"
pytest = "^7.3.0"
requests-mock = "^1.10.0"
setuptools = "^49.6.0"
typing-extensions = "^4.5.0"


[tool.semantic_release]
version_variable = "pyproject.toml:version" # version location
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
build_command = "poetry build"              # build dists
dist_path = "dist/"                         # where to put dists
upload_to_release = true                    # auto-create GitHub release
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
patch_without_tag = true                    # patch release by default
