[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "datajunction"
version = "0.0.1a7"
readme = "README.md"
repository = "https://github.com/DataJunction/dj"
description = "DataJunction client library for connecting to a DataJunction server"
authors = ["DataJunction Authors"]
license = "MIT"
packages = [
    { include = "datajunction" },
]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.coverage.run]
source = ['datajunction/']

[tool.isort]
src_paths = ["datajunction/", "tests/"]
profile = 'black'

[tool.poetry.dependencies]
python = "^3.8"
pandas = ">=2"
pydantic = ">=1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.2"
pylint = "^2.17.2"
pytest-asyncio = "^0.15.1"
pytest-cov = "^4.0.0"
pytest-integration = "^0.2.2"
pytest-mock = "^3.10.0"
pytest = "^7.3.0"
responses = "^0.23.1"
fastapi= "^0.70.1"
datajunction-server = {path = "../.."}
