description: Payments fact table.
type: source
columns:
  id:
    type: INT
  orderid:
    type: INT
  paymentmethod:
    type: STR
  status:
    type: STR
  amount:
    type: INT
  created:
    type: DATE
  _batched_at:
    type: TIMESTAMP
tables:
  postgres:
  - catalog: null
    schema: stripe
    table: payments
    cost: 1.0
