description: User dimension
type: dimension
query: SELECT id, full_name, age, country, gender, preferred_language, secret_number
  FROM basic.source.users
columns:
  id:
    type: INT
  full_name:
    type: STR
  age:
    type: INT
  country:
    type: STR
  gender:
    type: STR
  preferred_language:
    type: STR
  secret_number:
    type: FLOAT
