name: Generate OpenAPI Client
on:
  workflow_dispatch:
jobs:
  generate-python-client:
    runs-on: ubuntu-latest
    name: Generate Python Client
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install DJ
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate OpenAPI Spec
        run: ./scripts/generate-openapi.py -o openapi.json

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit OpenAPI Spec
        run: |
          git add openapi.json
          git commit -m "Updating OpenAPI Spec"

      - name: Generate Python client
        uses: openapi-generators/openapitools-generator-action@v1.4.0
        with:
          generator: python
          openapi-file: openapi.json
          config-file: ./.github/files/python-client-gen.yml
          command-args: --skip-validate-spec

      - name: Move client to right directory
        run: |
          mkdir -p ./openapi/python
          cp -r python-client/* ./openapi/python/
          rm -rf python-client

      - name: Set short sha
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Commit generated files
        run: |
          git add openapi/python/
          git commit -m "Update DJ Python client"
          git checkout -b ci-pr/python-client-${{ steps.sha.outputs.short_sha }}
          git push --set-upstream origin ci-pr/python-client-${{ steps.sha.outputs.short_sha }}

      - name: Open a PR
        run: gh pr create -B main -H ci-pr/python-client-${{ steps.sha.outputs.short_sha }} --title 'Update Python Client - ${{ steps.sha.outputs.short_sha }}' --body '(This PR was generated by a GitHub action)'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
