name: Generate OpenAPI Spec
on:
  workflow_dispatch:
jobs:
  generate-python-client:
    runs-on: ubuntu-latest
    name: Generate Python Client
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install DJ
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate OpenAPI Spec
        run: ./scripts/generate-openapi.py -o openapi.json

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit OpenAPI Spec
        run: |
          git add openapi.json
          git commit -m "Updating OpenAPI Spec"

      - name: Open a PR
        run: gh pr create -B main -H ci-pr/python-client-${{ steps.sha.outputs.short_sha }} --title 'Update OpenAPI Spec - ${{ steps.sha.outputs.short_sha }}' --body '(This PR was generated by a GitHub action)'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
