description: A fact table with comments
type: source
columns:
  id:
    type: INT
  user_id:
    type: INT
    dimension: basic.dimension.users
  timestamp:
    type: TIMESTAMP
  text:
    type: STR
tables:
  postgres:
  - catalog: null
    schema: basic
    table: comments
    cost: 10.0
  gsheets:
  - catalog: null
    schema: null
    table: comments
    cost: 100.0
